### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/Corrosion#1]
![image](https://user-images.githubusercontent.com/74786054/127653151-f1d54305-5bfe-4709-ad42-a0ef7ff6ac5b.png)
also,please provide a demo on heroku

**Comment by QuiteAFancyEmerald** [comment]
Are you sure that you are setting up everything correctly when using the demo?

**Comment by vackyton** [comment]
i am gonna make a vid and see if it works for me

**Comment by vackyton** [comment]
i am having a problem where it says script missing:start so did u forget to add the start sript or smt @QuiteAFancyEmerald

**Comment by deopdeop** [comment]
you need to specify a url

**Comment by vackyton** [comment]
? i am trying to run it on replit and its says script missing when i try to run so i can't even run it.

**Comment by QuiteAFancyEmerald** [comment]
You really are not setting it up correctly. I will try to explain things in the most simplest way.

First create a workspace and clone this repository. Next take the demo folder and work from there.
```
git clone https://github.com/titaniumnetwork-dev/Corrosion
cd demo
npm install
node index.js```

If you are setting things up for Heroku do the above and add an app.json and have the start script specified in package.json. (Auto-generated file)

**Comment by hyperdemon** [comment]
how do u do this is dumbass terms

**Comment by shirt-dev** [comment]
> how do u do this is dumbass terms

this is not a valid support channel for this
