### ISSUE TITLE
No deploy to heroku

### ISSUE THREAD

**Issue by ItCameFr0mMars** [titaniumnetwork-dev/Corrosion#2]
No deploy to heroku button, is there any way i can do this manually?

**Comment by boomermath** [comment]
You can just fork it and deploy to heroku via github, should work.

**Comment by QuiteAFancyEmerald** [comment]
Please read over #1 
This is merely a module but I explain its usage above with the demo.

**Comment by easella** [comment]
my repository:https://github.com/easella/Corrosion
