### ISSUE TITLE
SSL Problems

### ISSUE THREAD

**Issue by TheAlphaReturns** [titaniumnetwork-dev/Corrosion#29]
**Describe the bug**
These issues are on Heroku and railway.app hosting services.
The hosting platform's SSL causes js to not load, discord login screen to just be blank, and other bugs

![image](https://user-images.githubusercontent.com/61358474/156805777-61ac3e74-85cb-4ccb-a685-1ea751f651b0.png)
![image](https://user-images.githubusercontent.com/61358474/156805822-f4217b9c-6fcf-4d4a-9a2f-6ccfd63ca632.png)
![image](https://user-images.githubusercontent.com/61358474/156805887-4b9dc7ea-8d0a-4bf0-abf8-cf099da13478.png)
![image](https://user-images.githubusercontent.com/61358474/156805970-d3609894-1b49-4f37-87e2-00610ff56438.png)
...etc

However, if you connect with HTTP only, it will work, except there will be no HCapcha (no discord). And there will be that "Not Secure" banner. Confirmed that this is the hosting services fault because it works fine on localhost

**Comment by desplmfao** [comment]
use ultraviolet

**Comment by TheAlphaReturns** [comment]
ok, I hope it becomes something like an npm module soon!
