### ISSUE TITLE
heroku not working

### ISSUE THREAD

**Issue by easella** [titaniumnetwork-dev/Corrosion#3]
![image](https://user-images.githubusercontent.com/74786054/128427322-a23c1c22-1338-4ca5-adf9-494ac4680179.png)

**Comment by vackyton** [comment]
did u do npm install?

**Comment by QuiteAFancyEmerald** [comment]
#1 
I explain things here.

**Comment by shirt-dev** [comment]
@easella do not create multiple issues for the same question
