### ISSUE TITLE
Discord won't allow unmuting

### ISSUE THREAD

**Issue by obscurerev** [titaniumnetwork-dev/Corrosion#4]
Yes, I've enabled mic permissions and still won't unmute the icon.

**Comment by caracal-js** [comment]
This is a known issue that is unsolved.

**Comment by deopdeop** [comment]
Unmute doesn't work because webrtc isn't supported on corrosion

**Comment by caracal-js** [comment]
I've found out the reason is because of `Worklet.prototype.addModule` not being rewritten resulting in a syntax error. The solution is to rewrite the function which makes Discord VC fully work. This fix will be released in the next Corrosion update.
